#!/usr/bin/env python3
"""Generates native/uifont.inc (the anti-aliased type the screen pages draw with) from the Inter font.

Inter (c) The Inter Project Authors, SIL Open Font License 1.1 (see native/FONT-LICENSE.txt).
Needs Pillow and the Debian/Ubuntu package fonts-inter (or INTER_DIR pointing at the .otf files).

    python3 tools/gen_font.py            rewrites native/uifont.inc

Every glyph is stored as an 8-bit coverage map with its own width, so text is proportional and smooth.
The two big sizes hold only what clocks and numbers need. Digits share one width so a ticking clock does not jitter.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

DIR = os.environ.get("INTER_DIR", "/usr/share/fonts/opentype/inter")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "native", "uifont.inc")

FULL = [chr(c) for c in range(32, 127)]
NUM = list("0123456789:.-+% /")

#          name   file                       px  charset
FACES = [("XS", "Inter-SemiBold.otf",        9, FULL),
         ("S",  "Inter-Regular.otf",        11, FULL),
         ("M",  "Inter-Regular.otf",        13, FULL),
         ("MB", "Inter-SemiBold.otf",       13, FULL),
         ("L",  "InterDisplay-SemiBold.otf", 20, FULL),
         ("XL", "InterDisplay-SemiBold.otf", 30, NUM),
         ("XXL", "InterDisplay-SemiBold.otf", 46, NUM)]

GAMMA = 0.78          # light text on black looks thin when blended linearly; lift the coverage a little


def main():
    lines = ["/* Generated by tools/gen_font.py from Inter (SIL OFL 1.1, see FONT-LICENSE.txt). Do not edit. */",
             "/* Glyph = { width, height, left bearing, top (relative to the baseline, negative = above), advance, offset into the data }. */",
             ""]
    faces = []
    for name, fn, px, chars in FACES:
        font = ImageFont.truetype(os.path.join(DIR, fn), px)
        cap = -font.getbbox("H", anchor="ls")[1]
        digit_adv = max(round(font.getlength(d)) for d in "0123456789")
        data = bytearray()
        glyphs = []
        for ch in chars:
            adv = round(font.getlength(ch))
            if ch in "0123456789":
                adv = digit_adv
            if ch == ":":
                adv = max(adv, round(font.getlength(":")))
            x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
            w, h = max(0, x1 - x0), max(0, y1 - y0)
            off = len(data)
            if w and h and ch != " ":
                im = Image.new("L", (w, h), 0)
                ImageDraw.Draw(im).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
                for v in im.getdata():
                    data.append(min(255, int(round(255 * (v / 255.0) ** GAMMA))))
            else:
                w = h = 0
            glyphs.append((w, h, x0, y0, adv, off))
        faces.append((name, cap, px, chars, glyphs, len(data)))
        lines.append("static const uint8_t uf_%s_data[%d] = {" % (name, max(1, len(data))))
        for i in range(0, len(data), 24):
            lines.append("    " + ",".join("%d" % b for b in data[i:i + 24]) + ",")
        if not data:
            lines.append("    0")
        lines.append("};")
        lines.append("static const struct uglyph uf_%s_glyphs[%d] = {" % (name, len(glyphs)))
        for (w, h, bx, by, adv, off), ch in zip(glyphs, chars):
            lines.append("    { %d, %d, %d, %d, %d, %d }, /* %s */" % (w, h, bx, by, adv, off, repr(ch)[1:-1].replace("*/", "* /")))
        lines.append("};")
        lines.append("")
    lines.append("/* the faces, in the order of enum { T_XS, T_S, T_M, T_MB, T_L, T_XL, T_XXL } */")
    lines.append("static const struct uface uifaces[] = {")
    for name, cap, px, chars, glyphs, n in faces:
        first = ord(chars[0])
        lines.append("    { %d, %d, %d, %d, %d, uf_%s_glyphs, uf_%s_data }, /* %s */" % (cap, px, len(chars), 1 if chars is FULL or len(chars) == 95 else 0, first, name, name, name))
    lines.append("};")
    # the charset of each face, so a lookup can find a glyph: full faces are ASCII 32..126, the number faces are listed
    lines.append("static const char ui_numchars[] = \"%s\";" % "".join(NUM))
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT), sum(f[5] for f in faces), "bytes of glyph data")


if __name__ == "__main__":
    sys.exit(main())
